repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.4  # Use latest version
    hooks:
      # Run linter
      - id: ruff
        args: [--fix]
      # Run formatter (replaces Black)
      - id: ruff-format
