version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    environment:
      - MODEL_DIR=/models
      - FND_REPORT_TO=wandb,mlflow
    volumes:
      - ./runs/${MODEL_RUN:-roberta-kfr}/${MODEL_SUBDIR:-model}:/models:ro
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8000/healthz || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 20s

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    environment:
      - MODEL_DIR=/models
      - SAMPLES_FILE=/app/docs/test_samples.json
    volumes:
      - ./runs/${MODEL_RUN:-roberta-kfr}/${MODEL_SUBDIR:-model}:/models:ro
      - ./docs:/app/docs:ro
    ports:
      - "8501:8501"
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8501/ || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s
    depends_on:
      api:
        condition: service_healthy
