name: Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -e .

      - name: Run tests
        env:
          PYTHONPATH: src
        run: |
          python -m pytest tests/ -v --tb=short --cov=src/fnd --cov-report=term-missing --cov-report=xml

  # Auto-fix job: Only Ruff now!
  autofix:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install Ruff
      run: pip install ruff

    - name: Run Ruff formatter and linter
      run: |
        ruff format src/ tests/ scripts/
        ruff check --fix src/ tests/ scripts/

    - name: Commit and push changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "style: auto-format code with ruff"
        commit_user_name: "github-actions[bot]"
        commit_user_email: "github-actions[bot]@users.noreply.github.com"
        skip_dirty_check: false

  # Lint job: Check for non-fixable issues
  lint:
    runs-on: ubuntu-latest
    needs: [autofix]
    if: |
      always() &&
      (needs.autofix.result == 'success' || needs.autofix.result == 'skipped')

    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event_name == 'pull_request' && github.head_ref || github.ref }}

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install Ruff
      run: pip install ruff

    - name: Check formatting
      run: ruff format --check src/ tests/ scripts/

    - name: Check linting
      run: ruff check src/ tests/ scripts/
